apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-aifv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hjup-tenant/rhtap-demo-app/hacbs-test-project-aifv@sha256:e7d2239f454d251257ee34bb63d7fdee6f964b960efb8f059db4ac7637eafe0d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
