apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aifv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aifv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aifv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aifv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aifv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hjup-tenant/rhtap-demo-app/hacbs-test-project-aifv@sha256:e7d2239f454d251257ee34bb63d7fdee6f964b960efb8f059db4ac7637eafe0d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
